src/main/java/CalendarBean.java
import org.joda.time.DateTime;
import org.primefaces.event.SelectEvent;
import org.primefaces.model.DefaultScheduleEvent;
import org.primefaces.model.ScheduleEvent;
import org.primefaces.model.ScheduleModel;

import javax.faces.context.FacesContext;
import java.io.IOException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


public class CalendarBean {
    private List<Appointment> appointmentList;
    private List<Appointment> dayAppointmentlist = new ArrayList<>();
    private Appointment activeAppointment;
    private List<User> participants = new ArrayList<>();
    private ScheduleModel eventModel;
    private ScheduleEvent event = new DefaultScheduleEvent();
    private boolean showPrivate = true;
    private boolean showPublic = true;
    private boolean showDayList = false;



    private String newMessage;


    public Appointment getNewAppointment() {
        return activeAppointment;
    }

    public void setNewAppointment(Appointment newAppointment) {
        this.activeAppointment = newAppointment;
    }

    public List<Appointment> getAppointmentList() {
        if(appointmentList == null){
            appointmentList = DummyDB.getAppointmentList();
        }
       return appointmentList;
    }

    public void setAppointmentList(List<Appointment> appointmentList) {
        this.appointmentList = appointmentList;
        DummyDB.setAppointmentList(appointmentList);
    }

    public String addAppointment() {
        activeAppointment.getParticipants().add(new Participant(UserHelper.getCurrentUser(), Teilnahmestatus.yes, true));
        appointmentList.add(activeAppointment);
        DummyDB.setAppointmentList(appointmentList);
        return "success";
    }

    public void removeAppointment(Appointment appointment) {
        appointmentList.remove(appointment);
        DummyDB.setAppointmentList(appointmentList);
    }

    public Timestamp getCurrentDate() {
        return new Timestamp(System.currentTimeMillis());
    }

    public List<String> getZugangsverfahren() {
        return Zugangsverfahren.getAllZugangsverfahren();
    }

    public List<User> getAllUser() {
        return DummyDB.getUserWithoutCurrent();
    }

    public void setParticipants(List<String> userList) {
        List<Participant> pList = new ArrayList<>();
        for (String id : userList) {
            User u = DummyDB.getUserByID(Integer.parseInt(id));
            if (u != null) {
                Participant p = new Participant(u.getId(), null, false);
                pList.add(p);
            }
        }
        activeAppointment.setParticipants(pList);
    }

    public void setParticipants(int userList) {
        List<Participant> pList = new ArrayList<>();
        User u = DummyDB.getUserByID(userList);
        Participant p = new Participant(u.getId(), null, false);
        pList.add(p);
        activeAppointment.setParticipants(pList);
    }

    public List<Participant> getParticipants() {
        return activeAppointment.getParticipants();
    }

    public List<Integer> getParticipantsId() {
        List<Integer> idList = new ArrayList<>();
        for (Participant p : activeAppointment.getParticipants()) {
            idList.add(p.getUser().getId());
        }
        return idList;
    }

    public String setEditAppointment(int id) {
        activeAppointment = DummyDB.getAppointmentByID(id);
        return "edit";
    }

    public Appointment getEditAppointment() {
        return activeAppointment;
    }

    public String createNewAppointment() {
        activeAppointment = new Appointment();
        activeAppointment.setId(getAppointmentList().size());
        return "newEvent";
    }

    public String saveEditAppointment() {
        return "success";
    }


    public Appointment getShowAppointment() {
        return activeAppointment;
    }

    public String setShowAppointment(int id) {
        activeAppointment = DummyDB.getAppointmentByID(id);
        return "show";
    }

    public String sendMessage() {
        activeAppointment.addMessage(newMessage);
        return "message_send";
    }

    public void setNewMessage(String newMessage) {
        this.newMessage = newMessage;
    }

    public String getNewMessage() {
        newMessage = "";
        return newMessage;
    }

    public String setTeilnahme(String teilnahme) {
        for (Participant p : activeAppointment.getParticipants()
                ) {
            if (p.getUser().getId() == UserHelper.getCurrentUser().getId()) {
                p.setTeilnahmestatus(Teilnahmestatus.valueOf(teilnahme));
            }

        }
        return "reload";
    }

    public boolean renderTeilnahmechoice() {
        for (Participant p : activeAppointment.getParticipants()
                ) {
            if (p.getUser().getId() == UserHelper.getCurrentUser().getId()) {
                if (p.getTeilnahmestatus() == null) return true;
                else return false;
            }
        }
        return false;
    }

    public String getCurrentTeilnahme() {
        for (Participant p : activeAppointment.getParticipants()
                ) {
            if (p.getUser().getId() == UserHelper.getCurrentUser().getId()) {
                if (p.getTeilnahmestatus() == null) return null;
                else return p.getTeilnahmestatus().toString();
                //ToDo: Make Ajax for changing
            }
        }
        return null;
    }

    public ScheduleModel getEventModel() {
        if(showPrivate == true && showPublic == true) return DummyDB.getEventModel();
        else if (showPrivate == true) return DummyDB.getPrivateEventModel();
        else return DummyDB.getPublicEventModel();
    }


    public String onEventSelect(SelectEvent selectEvent) throws IOException {
        event = (ScheduleEvent) selectEvent.getObject();
        activeAppointment = DummyDB.getAppointmentByTitle(event.getTitle());
        FacesContext.getCurrentInstance().getExternalContext().redirect("showEvent.html");
        FacesContext.getCurrentInstance().responseComplete();

        return "edit";

    }

    public void onDateSelect(SelectEvent selectEvent) {
        event = new DefaultScheduleEvent("", (Date) selectEvent.getObject(), (Date) selectEvent.getObject());
        dayAppointmentlist = DummyDB.getDayAppointments(new DateTime(event.getStartDate()));
        showDayList = true;
    }

    public ScheduleEvent getEvent() {
        return event;
    }

    public void setEvent(ScheduleEvent event) {
        this.event = event;
    }


    public boolean isShowPrivate() {
        return showPrivate;
    }

    public void setShowPrivate(boolean showPrivate) {
        this.showPrivate = showPrivate;
    }

    public boolean isShowPublic() {
        return showPublic;
    }

    public void setShowPublic(boolean showPublic) {
        this.showPublic = showPublic;
    }

    public List<Appointment> getDayAppointmentlist() {
        return dayAppointmentlist;
    }

    public boolean showDayList(){
        return showDayList;
    }
}

src/main/java/ChatBean.java
public class ChatBean {
}

src/main/java/UserBean.java
public class UserBean {
}

src/main/webapp/WEB-INF/tags/confirmationDialog.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

	<!-- confirmation dialog for deleting objects, etc. -->
	
	<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
		<h:form>
			<p:commandButton value="Ja" type="button"
				styleClass="ui-confirmdialog-yes"/>
			<p:commandButton value="Nein" type="button" 
				styleClass="ui-confirmdialog-no"/>
		</h:form>
	</p:confirmDialog>
	
</html>

src/main/webapp/WEB-INF/tags/head.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html">
	<h:head>
		<!-- Metainformation -->
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
	
		<!-- Title -->
		<title>Pool2 Calendar</title>
		
		<!-- Favicon
		<link rel="shortcut icon" type="image/x-icon" href="#{resource['images/favicon.ico']}"/>
		-->

		<!-- Stylesheets -->
		<h:outputStylesheet library="webjars" name="bootstrap/3.3.6/css/bootstrap.min-jsf.css" />
	    <h:outputStylesheet library="webjars" name="bootstrap/3.3.6/css/bootstrap-theme.min-jsf.css" />
	    <h:outputStylesheet library="webjars" name="font-awesome/4.5.0/css/font-awesome.min-jsf.css" />
	    
	    <h:outputStylesheet library="css" name="main.css" />
	    <h:outputStylesheet library="css" name="forms.css" />
	    <h:outputStylesheet library="css" name="overview.css" />
	    <h:outputStylesheet library="css" name="loginLogout.css" />
	    <h:outputStylesheet library="css" name="testprocess.css" />
	</h:head>
</html>

src/main/webapp/WEB-INF/tags/js-footer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html">

<!-- Bootstrap & Jquery JS-->
<h:outputScript library="primefaces" name="jquery/jquery.js"
	target="head" />
<h:outputScript library="webjars"
	name="bootstrap/3.3.6/js/bootstrap.min.js" />
<h:outputScript library="js" name="primefacesLocale.js" />
</html>

src/main/webapp/editEvent.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:sefb="http://sefb.com/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<sefb:head />

<h:body>

    <div class="loginFormContainer">

        <div class="loginFormWindow">
            <h:form id="loginForm">
                <div class="form-group">
                    <h:outputLabel for="name" value="Name:"/>
                    <p:inputText id="name" class="inputText" required="true"
                                 requiredMessage="Der Veranstaltungsname darf nicht leer sein!"
                                 value="#{calendarBean.editAppointment.title}"
                    />
                    <h:outputLabel for="place" value="Ort:"/>
                    <p:inputText id="place" class="inputText" value="#{calendarBean.editAppointment.place}"/>

                </div>

                <h:outputLabel for="note" value="Note:"/>
                <h:inputTextarea id="note" class="inputText" value="#{calendarBean.editAppointment.note}"/>

                <h:outputLabel for="beginn" value="Beginn:"/>
                <p:calendar id="beginn" value="#{calendarBean.editAppointment.beginn}" pattern="MM/dd/yyyy HH:mm:ss" />
                <h:outputLabel for="end" value="Beginn:"/>
                <p:calendar id="end" value="#{calendarBean.editAppointment.end}" pattern="MM/dd/yyyy HH:mm:ss" />
                <br/>
                <h:outputLabel for="region" value="Region:"/>
                <p:inputText id="region" class="inputText" value="#{calendarBean.editAppointment.region}"/>
                <h:outputLabel for="bereich" value="Bereich:"/>
                <p:inputText id="bereich" class="inputText" value="#{calendarBean.editAppointment.bereich}"/>
                <h:outputLabel for="gruppe" value="Gruppe:"/>

                <p:selectOneMenu id="gruppe" required="true"
                                 value="#{calendarBean.editAppointment.gruppe}" class="inputText">
                    <f:selectItem itemValue="oeffentlich" itemLabel="Öffentlich"/>
                    <f:selectItem itemValue="private" itemLabel="Privat"/>
                </p:selectOneMenu>


                <h:outputLabel for="Zugangsverfahren" value="Zugangsverfahren:"/>
                <p:selectOneMenu id="Zugangsverfahren" required="true"
                                 requiredMessage="Wählen Sie ein Zugangsverfahren"
                                 value="#{calendarBean.editAppointment.zugangsverfahren}" class="inputText">
                    <f:selectItem itemValue="free" itemLabel="frei zugänglich"/>
                    <f:selectItem itemValue="registration" itemLabel="Anmeldung erforderlich"/>
                    <f:selectItem itemValue="candidator" itemLabel="Bewerbung erforderlich"/>
                </p:selectOneMenu>

                <h:outputLabel for="editor" value="Teilnehmer:"/>
                <h:selectManyListbox id="editor" value="#{calendarBean.participantsId}">
                    <f:selectItems value="#{calendarBean.allUser}" var="user" itemLabel="#{user.name}" itemValue="#{user.id}" />
                </h:selectManyListbox>


                <h:commandButton
                        class="btn btn-primary pull-right loginBtn"
                        value="Speichern"  action="#{calendarBean.saveEditAppointment}" />

            </h:form>

        </div>

        <div class="loginFooter">
        </div>
    </div>
    <sefb:js-footer />
</h:body>
</html>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:sefb="http://sefb.com/facelets"
      xml:lang="en" lang="en">
<sefb:head/>
<body>


<div class="ui-g">
    <div class="ui-g-12 ui-md-2">
        <h:form id="form">
            <h:commandButton id="save_btn" value="Neu"
                             action="#{calendarBean.createNewAppointment()}"
            /><br/>

            <p:outputLabel for="@next" value="Private: "/>
            <p:selectBooleanCheckbox value="#{calendarBean.showPrivate}">
                <p:ajax update="scheduleLocale"/>
            </p:selectBooleanCheckbox>
            <br/>
            <p:outputLabel for="@next" value="Öffentlich: "/>
            <p:selectBooleanCheckbox value="#{calendarBean.showPublic}">
                <p:ajax update="scheduleLocale"/>
            </p:selectBooleanCheckbox>
        </h:form>
        <br/>
    </div>
    <div class="ui-g-12 ui-md-8 ui-g-nopad">
        <p:schedule id="scheduleLocale" value="#{calendarBean.eventModel}" styleClass="scheduler" leftHeaderTemplate=""
                    rightHeaderTemplate="prev, next today">
            <p:ajax event="eventSelect" listener="#{calendarBean.onEventSelect}" value="edit"/>
            <p:ajax event="dateSelect" listener="#{calendarBean.onDateSelect}" update="dailyEvents"/>
        </p:schedule>
    </div>

<div class="ui-g-12 ui-md-2 ui-g-nopad">
    <h:form id="dailyEvents" >
        <p:dataTable var="appointment" value="#{calendarBean.dayAppointmentlist}">
            <p:column headerText="Titel">
                <h:outputText value="#{appointment.title}"/>
            </p:column>
            <p:column headerText="Beginn">
                <h:outputText value="#{appointment.beginn}"/>
            </p:column>
            <p:column headerText="End">
                <h:outputText value="#{appointment.end}"/>
            </p:column>
            <p:column headerText="Edit">
                <p:commandButton action="#{calendarBean.setEditAppointment(appointment.id)}" value="Edit"/>
            </p:column>
            <p:column headerText="Show">
                <p:commandButton action="#{calendarBean.setShowAppointment(appointment.id)}" value="Show"/>
            </p:column>
        </p:dataTable>
    </h:form>
</div>
</div>


</body>
</html>

src/main/webapp/newEvent.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
	  xmlns:h="http://java.sun.com/jsf/html"
	  xmlns:p="http://primefaces.org/ui"
	  xmlns:sefb="http://sefb.com/facelets"
	  xmlns:f="http://xmlns.jcp.org/jsf/core">

<sefb:head />

<h:body>

	<div class="loginFormContainer">

		<div class="loginFormWindow">
			<h:form id="loginForm">
				<div class="form-group">
				<h:outputLabel for="name" value="Name:"/>
				<p:inputText id="name" class="inputText" required="true"
							 requiredMessage="Der Veranstaltungsname darf nicht leer sein!"
							 value="#{calendarBean.newAppointment.title}"
				/>
				<h:outputLabel for="place" value="Ort:"/>
				<p:inputText id="place" class="inputText" value="#{calendarBean.newAppointment.place}"/>

				</div>

				<h:outputLabel for="note" value="Note:"/>
				<h:inputTextarea id="note" class="inputText" value="#{calendarBean.newAppointment.note}"/>

				<h:outputLabel for="beginn" value="Beginn:"/>
				<p:calendar id="beginn" value="#{calendarBean.newAppointment.beginn}" pattern="MM/dd/yyyy HH:mm:ss" />
				<h:outputLabel for="end" value="Beginn:"/>
				<p:calendar id="end" value="#{calendarBean.newAppointment.end}" pattern="MM/dd/yyyy HH:mm:ss" />
				<br/>
				<h:outputLabel for="region" value="Region:"/>
				<p:inputText id="region" class="inputText" value="#{calendarBean.newAppointment.region}"/>
				<h:outputLabel for="bereich" value="Bereich:"/>
				<p:inputText id="bereich" class="inputText" value="#{calendarBean.newAppointment.bereich}"/>
				<h:outputLabel for="gruppe" value="Gruppe:"/>

				<p:selectOneMenu id="gruppe" required="true"
								 value="#{calendarBean.newAppointment.gruppe}" class="inputText">
					<f:selectItem itemValue="oeffentlich" itemLabel="Öffentlich"/>
					<f:selectItem itemValue="private" itemLabel="Privat"/>
				</p:selectOneMenu>


				<h:outputLabel for="Zugangsverfahren" value="Zugangsverfahren:"/>
				<p:selectOneMenu id="Zugangsverfahren" required="true"
								 requiredMessage="Wählen Sie ein Zugangsverfahren"
								 value="#{calendarBean.newAppointment.zugangsverfahren}" class="inputText">
					<f:selectItem itemValue="free" itemLabel="frei zugänglich"/>
					<f:selectItem itemValue="registration" itemLabel="Anmeldung erforderlich"/>
					<f:selectItem itemValue="candidator" itemLabel="Bewerbung erforderlich"/>
				</p:selectOneMenu>

				<h:outputLabel for="editor" value="Teilnehmer:"/>
				<h:selectManyListbox id="editor" value="#{calendarBean.participants}">
					<f:selectItems value="#{calendarBean.allUser}" var="user" itemLabel="#{user.name}" itemValue="#{user.id}" />
				</h:selectManyListbox>


				<h:commandButton
					class="btn btn-primary pull-right loginBtn"
					value="Speichern"  action="#{calendarBean.addAppointment}" />

			</h:form>

		</div>

		<div class="loginFooter">
		</div>
	</div>
	<sefb:js-footer />
</h:body>
</html>

src/main/webapp/showEvent.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:sefb="http://sefb.com/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      >

<sefb:head />

<h:body>

    <div class="loginFormContainer">

        <div class="loginFormWindow">
            <h:form id="loginForm">
                <div class="form-group">

                    <h:commandButton value="Zurück"  action="back" /><br/>
                    <p:commandButton action="edit" value="Edit"/><br/>


                    <h:form rendered="#{calendarBean.renderTeilnahmechoice()}">
                    <h:commandButton value="Zusagen"  action="#{calendarBean.setTeilnahme('yes')}" />
                    <h:commandButton value="Vielleicht"   action="#{calendarBean.setTeilnahme('no')}" />
                    <h:commandButton value="Absagen"   action="#{calendarBean.setTeilnahme('maybe')}" />
                    </h:form>

                    <h:form rendered="#{calendarBean.currentTeilnahme != null}">
                        <p:selectOneMenu value="#{calendarBean.currentTeilnahme}" class="inputText">
                            <f:selectItem itemValue="Zusage" itemLabel="Zusage"/>
                            <f:selectItem itemValue="Absage" itemLabel="Absage"/>
                            <f:selectItem itemValue="Vielleicht" itemLabel="Vielleicht"/>
                        </p:selectOneMenu>
                    </h:form>




                    <h:outputLabel for="name" value="Name:"/>
                    <p:inputText id="name" disabled="true"
                                 value="#{calendarBean.showAppointment.title}"
                    />
                    <h:outputLabel for="place" value="Ort:"/>
                    <p:inputText id="place" class="inputText" disabled="true" value="#{calendarBean.showAppointment.place}"/>

                </div>

                <h:outputLabel for="note" value="Note:"/>
                <h:inputTextarea id="note" class="inputText" disabled="true" value="#{calendarBean.showAppointment.note}"/>

                <h:outputLabel for="beginn" value="Beginn:"/>
                <p:calendar id="beginn" value="#{calendarBean.showAppointment.beginn}" pattern="MM/dd/yyyy HH:mm:ss" disabled="true" />
                <h:outputLabel for="end" value="Beginn:"/>
                <p:calendar id="end" value="#{calendarBean.showAppointment.end}" pattern="MM/dd/yyyy HH:mm:ss" disabled="true" />
                <br/>
                <h:outputLabel for="region" value="Region:" />
                <p:inputText id="region" class="inputText" value="#{calendarBean.showAppointment.region}" disabled="true"/>
                <h:outputLabel for="bereich" value="Bereich:"/>
                <p:inputText id="bereich" class="inputText" value="#{calendarBean.showAppointment.bereich}" disabled="true"/>
                <h:outputLabel for="gruppe" value="Gruppe:"/>

                <p:selectOneMenu id="gruppe" required="true"
                                 value="#{calendarBean.showAppointment.gruppe}" class="inputText" disabled="true">
                    <f:selectItem itemValue="oeffentlich" itemLabel="Öffentlich"/>
                    <f:selectItem itemValue="private" itemLabel="Privat"/>
                </p:selectOneMenu>


                <h:outputLabel for="Zugangsverfahren" value="Zugangsverfahren:" />
                <p:selectOneMenu id="Zugangsverfahren" disabled="true"
                                 value="#{calendarBean.showAppointment.zugangsverfahren}" class="inputText">
                    <f:selectItem itemValue="free" itemLabel="frei zugänglich"/>
                    <f:selectItem itemValue="registration" itemLabel="Anmeldung erforderlich"/>
                    <f:selectItem itemValue="candidator" itemLabel="Bewerbung erforderlich"/>
                </p:selectOneMenu>

                <h:outputLabel for="teilnehmer" value="Teilnehmer:"/>
                <p:dataTable id="teilnehmer" var="participant" styleClass="noHeader" style="width:500px;"  value="#{calendarBean.participants}">
                    <p:column style="height:30px;">
                        <h:outputText value="#{participant.user.name}" />
                    </p:column>

                    <p:column  style="width:50px;">
                        <h:outputText value="#{participant.teilnahmestatus}" />
                    </p:column>

                    <p:column style="width:50px;">
                    </p:column>
                </p:dataTable>





            </h:form>


            <h:form>
                <h:outputLabel value="Chat:"/>
                <c:forEach var="message" items="#{calendarBean.showAppointment.messages}">
                            <h:outputText value="#{message.sender.name} am #{message.created_String}: #{message.message}" /><br/>
                </c:forEach>
            </h:form>

            <h:form id="chat">

            <h:outputLabel for="message" value="Message:"/>
            <p:inputText id="message" class="inputText" value="#{calendarBean.newMessage}"/>
                <h:commandButton value="Senden"  action="#{calendarBean.sendMessage()}" />
            </h:form>

        </div>

        <div class="loginFooter">
        </div>
    </div>
    <sefb:js-footer />
</h:body>
</html>